"""
Missing BrAPI models not generated by datamodel-codegen.

These models are endpoint-specific response types that weren't included
in the BrAPI-Schema JSON schemas, but are needed for actual API usage.

Extracted from the old brapi_v2/core/models.py (Pydantic v1) and
manually converted to Pydantic v2.
"""

from typing import List, Optional, Dict
from pydantic import BaseModel, Field, AnyUrl
from datetime import date


class Service(BaseModel):
    """
    Metadata about a single BrAPI endpoint/service.
    """
    contentTypes: Optional[List[str]] = Field(
        None, description='The possible content types returned by the service'
    )
    dataTypes: Optional[List[str]] = Field(
        None, description='The possible data types returned by the service'
    )
    methods: List[str] = Field(
        ..., description='The possible HTTP methods for this service', example=['GET', 'POST']
    )
    service: str = Field(
        ..., description='The relative path of the service', example='germplasm'
    )
    versions: List[str] = Field(
        ..., description='The supported BrAPI versions for this service', example=['2.0']
    )


class ServerInfo(BaseModel):
    """
    Server information response from /serverinfo endpoint.

    Provides metadata about the BrAPI server including available calls,
    organization info, and server description.
    """
    calls: List[Service] = Field(
        ..., description='Array of available calls on this server'
    )
    contactEmail: Optional[str] = Field(
        None,
        description='A contact email address for this server management',
        example='contact@institute.org',
    )
    documentationURL: Optional[str] = Field(
        None,
        description='A URL to the human readable documentation of this object',
        example='institute.org/server',
    )
    location: Optional[str] = Field(
        None,
        description='Physical location of this server (ie. City, Country)',
        example='USA',
    )
    organizationName: Optional[str] = Field(
        None,
        description='The name of the organization that manages this server and data',
        example='The Institute',
    )
    organizationURL: Optional[str] = Field(
        None,
        description='The URL of the organization that manages this server and data',
        example='institute.org/home',
    )
    serverDescription: Optional[str] = Field(
        None,
        description='A description of this server',
        example='The BrAPI Test Server',
    )
    serverName: Optional[str] = Field(
        None, description='The name of this server', example='The BrAPI Test Server'
    )


class ServerInfoResponseResult(BaseModel):
    """Wrapper for ServerInfo result"""
    data: List[ServerInfo]


class CommonCropNamesResponseResult(BaseModel):
    """
    Response result for common crop names endpoint.
    """
    data: List[str] = Field(
        ...,
        description='List of common crop names available in the database',
        example=['Maize', 'Wheat', 'Rice']
    )


class ObservationUnitHierarchyLevel(BaseModel):
    """
    Observation unit hierarchy level.
    """
    levelName: Optional[str] = Field(
        None,
        description='A name for this level',
        example='plot',
    )
    levelOrder: Optional[int] = Field(
        None,
        description='Level number for this level. Lower numbers represent lower (more specific) levels.',
        example=1,
    )


class StudyType(BaseModel):
    """
    A study type entity.
    """
    description: Optional[str] = Field(
        None,
        description='Description of this study type',
    )
    name: str = Field(
        ...,
        description='Name of this study type',
        example='Yield Trial'
    )


class StudyTypesResponseResult(BaseModel):
    """Response result for study types endpoint"""
    data: List[StudyType]


class PedigreeNode(BaseModel):
    """
    Represents a single node in a pedigree tree.
    """
    crossingPlan: Optional[str] = None
    crossingYear: Optional[int] = None
    familyCode: Optional[str] = None
    germplasmDbId: str = Field(..., description='Germplasm database ID')
    germplasmName: str = Field(..., description='Germplasm name')
    pedigree: Optional[str] = Field(
        None,
        description='The string representation of the pedigree'
    )
    parents: Optional[List['PedigreeNode']] = Field(
        None,
        description='List of parent nodes'
    )
    progeny: Optional[List['PedigreeNode']] = Field(
        None,
        description='List of progeny nodes'
    )
    siblings: Optional[List['PedigreeNode']] = Field(
        None,
        description='List of sibling nodes'
    )


# Allow forward references
PedigreeNode.model_rebuild()


class ListSummary(BaseModel):
    """Summary of a BrAPI list"""
    dateCreated: Optional[date] = None
    dateModified: Optional[date] = None
    listDbId: str
    listDescription: Optional[str] = None
    listName: str
    listOwnerName: Optional[str] = None
    listOwnerPersonDbId: Optional[str] = None
    listSize: Optional[int] = None
    listSource: Optional[str] = None
    listType: Optional[str] = None


class ListDetails(BaseModel):
    """Detailed list with items"""
    data: Optional[List[str]] = Field(
        None,
        description='List item database IDs'
    )
